// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_create_user_open_api_v1_users_open_post
 */
export type BodyCreateUserOpenApiV1UsersOpenPost = {
    /**
     * Password
     */
    password: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string;
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string;
    /**
     * Client Secret
     */
    client_secret?: string;
};

/**
 * Body_reset_password_api_v1_reset_password__post
 */
export type BodyResetPasswordApiV1ResetPasswordPost = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Body_update_user_me_api_v1_users_me_put
 */
export type BodyUpdateUserMeApiV1UsersMePut = {
    /**
     * Password
     */
    password?: string;
    /**
     * Full Name
     */
    full_name?: string;
    /**
     * Email
     */
    email?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * Msg
 */
export type Msg = {
    /**
     * Msg
     */
    msg: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * User
 */
export type User = {
    /**
     * Email
     */
    email?: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string;
    /**
     * Id
     */
    id?: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string;
    /**
     * Password
     */
    password?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type TestTokenApiV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenApiV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type TestTokenApiV1LoginTestTokenPostResponse = TestTokenApiV1LoginTestTokenPostResponses[keyof TestTokenApiV1LoginTestTokenPostResponses];

export type RecoverPasswordApiV1PasswordRecoveryEmailPostData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostError = RecoverPasswordApiV1PasswordRecoveryEmailPostErrors[keyof RecoverPasswordApiV1PasswordRecoveryEmailPostErrors];

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponses = {
    /**
     * Successful Response
     */
    200: Msg;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponse = RecoverPasswordApiV1PasswordRecoveryEmailPostResponses[keyof RecoverPasswordApiV1PasswordRecoveryEmailPostResponses];

export type ResetPasswordApiV1ResetPasswordPostData = {
    body: BodyResetPasswordApiV1ResetPasswordPost;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type ResetPasswordApiV1ResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1ResetPasswordPostError = ResetPasswordApiV1ResetPasswordPostErrors[keyof ResetPasswordApiV1ResetPasswordPostErrors];

export type ResetPasswordApiV1ResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: Msg;
};

export type ResetPasswordApiV1ResetPasswordPostResponse = ResetPasswordApiV1ResetPasswordPostResponses[keyof ResetPasswordApiV1ResetPasswordPostResponses];

export type ReadUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type ReadUsersApiV1UsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersApiV1UsersGetError = ReadUsersApiV1UsersGetErrors[keyof ReadUsersApiV1UsersGetErrors];

export type ReadUsersApiV1UsersGetResponses = {
    /**
     * Response Read Users Api V1 Users  Get
     *
     * Successful Response
     */
    200: Array<User>;
};

export type ReadUsersApiV1UsersGetResponse = ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ReadUserMeApiV1UsersMeGetResponse = ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type UpdateUserMeApiV1UsersMePutData = {
    body?: BodyUpdateUserMeApiV1UsersMePut;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateUserMeApiV1UsersMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeApiV1UsersMePutError = UpdateUserMeApiV1UsersMePutErrors[keyof UpdateUserMeApiV1UsersMePutErrors];

export type UpdateUserMeApiV1UsersMePutResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateUserMeApiV1UsersMePutResponse = UpdateUserMeApiV1UsersMePutResponses[keyof UpdateUserMeApiV1UsersMePutResponses];

export type CreateUserOpenApiV1UsersOpenPostData = {
    body: BodyCreateUserOpenApiV1UsersOpenPost;
    path?: never;
    query?: never;
    url: '/api/v1/users/open';
};

export type CreateUserOpenApiV1UsersOpenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserOpenApiV1UsersOpenPostError = CreateUserOpenApiV1UsersOpenPostErrors[keyof CreateUserOpenApiV1UsersOpenPostErrors];

export type CreateUserOpenApiV1UsersOpenPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserOpenApiV1UsersOpenPostResponse = CreateUserOpenApiV1UsersOpenPostResponses[keyof CreateUserOpenApiV1UsersOpenPostResponses];

export type ReadUserByIdApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ReadUserByIdApiV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdApiV1UsersUserIdGetError = ReadUserByIdApiV1UsersUserIdGetErrors[keyof ReadUserByIdApiV1UsersUserIdGetErrors];

export type ReadUserByIdApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = ReadUserByIdApiV1UsersUserIdGetResponses[keyof ReadUserByIdApiV1UsersUserIdGetResponses];

export type UpdateUserApiV1UsersUserIdPutData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserApiV1UsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1UsersUserIdPutError = UpdateUserApiV1UsersUserIdPutErrors[keyof UpdateUserApiV1UsersUserIdPutErrors];

export type UpdateUserApiV1UsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateUserApiV1UsersUserIdPutResponse = UpdateUserApiV1UsersUserIdPutResponses[keyof UpdateUserApiV1UsersUserIdPutResponses];

export type TestCeleryApiV1UtilsTestCeleryPostData = {
    body: Msg;
    path?: never;
    query?: never;
    url: '/api/v1/utils/test-celery/';
};

export type TestCeleryApiV1UtilsTestCeleryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestCeleryApiV1UtilsTestCeleryPostError = TestCeleryApiV1UtilsTestCeleryPostErrors[keyof TestCeleryApiV1UtilsTestCeleryPostErrors];

export type TestCeleryApiV1UtilsTestCeleryPostResponses = {
    /**
     * Successful Response
     */
    201: Msg;
};

export type TestCeleryApiV1UtilsTestCeleryPostResponse = TestCeleryApiV1UtilsTestCeleryPostResponses[keyof TestCeleryApiV1UtilsTestCeleryPostResponses];

export type TestEmailApiV1UtilsTestEmailPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type TestEmailApiV1UtilsTestEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailApiV1UtilsTestEmailPostError = TestEmailApiV1UtilsTestEmailPostErrors[keyof TestEmailApiV1UtilsTestEmailPostErrors];

export type TestEmailApiV1UtilsTestEmailPostResponses = {
    /**
     * Successful Response
     */
    201: Msg;
};

export type TestEmailApiV1UtilsTestEmailPostResponse = TestEmailApiV1UtilsTestEmailPostResponses[keyof TestEmailApiV1UtilsTestEmailPostResponses];

export type ReadItemsApiV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ReadItemsApiV1ItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemsApiV1ItemsGetError = ReadItemsApiV1ItemsGetErrors[keyof ReadItemsApiV1ItemsGetErrors];

export type ReadItemsApiV1ItemsGetResponses = {
    /**
     * Response Read Items Api V1 Items  Get
     *
     * Successful Response
     */
    200: Array<Item>;
};

export type ReadItemsApiV1ItemsGetResponse = ReadItemsApiV1ItemsGetResponses[keyof ReadItemsApiV1ItemsGetResponses];

export type CreateItemApiV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type CreateItemApiV1ItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError = CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type CreateItemApiV1ItemsPostResponse = CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type DeleteItemApiV1ItemsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type DeleteItemApiV1ItemsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemApiV1ItemsIdDeleteError = DeleteItemApiV1ItemsIdDeleteErrors[keyof DeleteItemApiV1ItemsIdDeleteErrors];

export type DeleteItemApiV1ItemsIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type DeleteItemApiV1ItemsIdDeleteResponse = DeleteItemApiV1ItemsIdDeleteResponses[keyof DeleteItemApiV1ItemsIdDeleteResponses];

export type ReadItemApiV1ItemsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ReadItemApiV1ItemsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemApiV1ItemsIdGetError = ReadItemApiV1ItemsIdGetErrors[keyof ReadItemApiV1ItemsIdGetErrors];

export type ReadItemApiV1ItemsIdGetResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type ReadItemApiV1ItemsIdGetResponse = ReadItemApiV1ItemsIdGetResponses[keyof ReadItemApiV1ItemsIdGetResponses];

export type UpdateItemApiV1ItemsIdPutData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type UpdateItemApiV1ItemsIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemApiV1ItemsIdPutError = UpdateItemApiV1ItemsIdPutErrors[keyof UpdateItemApiV1ItemsIdPutErrors];

export type UpdateItemApiV1ItemsIdPutResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type UpdateItemApiV1ItemsIdPutResponse = UpdateItemApiV1ItemsIdPutResponses[keyof UpdateItemApiV1ItemsIdPutResponses];
